### PR TITLE
Add link validation to validateNotificationObject

### PR DESCRIPTION
**Pull request by THaGKI9**
### Description
As exported in `interfaces.ts`, `CustomNotificationObject` was suppose to support `link` parameter. The fact is that `API::notification(CustomNotificationObject)` doesn't treat `link` as a valid parameter and do validation for it, instead, an exception suggested that `link` is invalid parameter.

This change to to add `link` parameter` into the validation.

I didn't update the verison field in `package.json` cuz I think it's better let the repo maintainers to decide when to bump the version and which version to bump.

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works

### CODE REVIEW

**Comment by THaGKI9** [comment]
Gentle ping on this one

**Comment by aaronbarnardsound** [comment]
Thanks for the PR and sorry for taking so long to reply! Will try to get this reviewed and released in the next few days.

**Comment by Adamj1232** [comment]
Looks good and working well, thank you @THaGKI9 ! If we could bump the feature version in package.json to `1.9.4-0.0.1` that would be great and I will get that merged

**Comment by THaGKI9** [comment]
thank you arron and adam! looking forward to the merge!

**Comment by Adamj1232** [comment]
@THaGKI9 apologies, I should have been more clear in the above comment, could you update the version and push?
Also, I see a new file with changes `.github/workflows/issue-to-notion.yml` could you revert and scope to the validation changes when you have a moment?
Thanks!

**Comment by THaGKI9** [comment]
Thanks for clarification! I've created another PR from `develop` branch because this PR was checkout from the `master` branch and that's why the notion file shows up. 

https://github.com/blocknative/notify/pull/234

**Pull request closed without merging**
